parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module

env:
  es6: true
  node: true

extends:
  - airbnb-base # switch to airbnb-typescript/base
  - eslint:recommended
  # - plugin:@typescript-eslint/recommended
  # - plugin:@typescript-eslint/recommended-requiring-type-checking
  # plugin:import/typescript
  # plugin:jest/recommended
  # prettier
  # prettier/@typescript-eslint
  - prettier # must go last, to turn off some previous rules

rules:
  prefer-arrow-callback: error
  func-names: 0
  no-use-before-define: 0
  require-await: error
