parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  project: tsconfig.json

env:
  es6: true
  node: true

extends:
  - airbnb-typescript/base
  - eslint:recommended
  # - plugin:@typescript-eslint/recommended
  # - plugin:@typescript-eslint/recommended-requiring-type-checking
  # - plugin:jest/recommended
  # - prettier/@typescript-eslint
  - prettier # must go last, to turn off some previous rules

rules:
  prefer-arrow-callback: error
  func-names: 0
  no-use-before-define: 0
  require-await: error
  '@typescript-eslint/no-use-before-define': 0
# TODO
# Not sure if need to migrate chai plugin too
# Get tests working
