openapi: 3.0.0
info:
  title: Example OpenApi 3 spec
  description: Has server variables
  version: 0.1.0
servers:
  - url: /{variableInPath}
    description: server url with 1 server variable in the path
    variables:
      variableInPath:
        default: defaultValueForVariableInPath
        enum:
          - enumValueForVariableInPath
  - url: /{firstVariableInPath}/{secondVariableInPath}
    description: server url with multiple server variables in the path
    variables:
      firstVariableInPath:
        default: defaultValueForFirstVariableInPath
      secondVariableInPath:
        default: defaultValueForSecondVariableInPath
  - url: https://{hostVariable}.com:{portVariable}/
    description: server url with server variables only before the path
    variables:
      hostVariable:
        default: defaultValueForHostVariable
      portVariable:
        default: '1234'
  - url: https://{hostVariable}.com:{portVariable}/{variableInDifferentPath}
    description: server url with server variables before and after the path
    variables:
      hostVariable:
        default: defaultValueForHostVariable
      portVariable:
        default: '1234'
      variableInDifferentPath:
        default: defaultValueForVariableInDifferentPath
paths:
  /endpointPath:
    get:
      responses:
        200:
          description: Response body should be a string
          content:
            application/json:
              schema:
                type: string
